url: "/recipes" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://fackamata.github.io" # the subpath of your site, e.g. /blog
title: "recette de famille" # the name of your site, e.g. ACME Corp.

collections:
  recipes:
    output: true
    permalink: /:collection/:categories/:path
