url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/recipes" # the subpath of your site, e.g. /blog
title: "recette de famille" # the name of your site, e.g. ACME Corp.

github: [metadata]
description: >- # this means to ignore newlines until "baseurl:"
  Simple recipe website with Jekyll.
collections:
  recipes:
    output: true
    permalink: /:collection/:categories/:path
